import logging
import os
import sqlite3
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from opentelemetry import metrics, trace
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.exporter.otlp.proto.http._log_exporter import OTLPLogExporter


# I use the same resource for traces, metrics, and logs so all telemetry
# generated by this application can be identified as the same service.
resource = Resource.create({
    "service.name": "order-tracker"
})


# ---------------------------------------------------------
# Tracing
# ---------------------------------------------------------

# I create a tracer provider for the Order Tracker service.
tracer_provider = TracerProvider(resource=resource)
trace.set_tracer_provider(tracer_provider)

# I send traces to the OpenTelemetry Collector using OTLP over HTTP.
trace_exporter = OTLPSpanExporter(
    endpoint=os.getenv(
        "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
        "http://otel-collector:4318/v1/traces"
    )
)

# I use a batch processor so spans are exported efficiently.
tracer_provider.add_span_processor(
    BatchSpanProcessor(trace_exporter)
)

tracer = trace.get_tracer(__name__)


# ---------------------------------------------------------
# Metrics
# ---------------------------------------------------------

# I send application metrics to the OpenTelemetry Collector.
metric_exporter = OTLPMetricExporter(
    endpoint=os.getenv(
        "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
        "http://otel-collector:4318/v1/metrics"
    )
)

# Metrics are exported every five seconds so I can observe changes
# quickly while testing the application.
metric_reader = PeriodicExportingMetricReader(
    metric_exporter,
    export_interval_millis=5000
)

meter_provider = MeterProvider(
    resource=resource,
    metric_readers=[metric_reader]
)

metrics.set_meter_provider(meter_provider)

meter = metrics.get_meter(__name__)

# This counter tracks order lookup requests and their HTTP status codes.
# It will later help me detect user-facing lookup failures.
order_lookup_counter = meter.create_counter(
    name="order_lookup_requests_total",
    description="Total number of order lookup requests",
    unit="1"
)


# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------

# I use a dedicated logger for application events.
logger = logging.getLogger("order-tracker")
logger.setLevel(logging.INFO)

# I clear existing handlers so they are not added more than once
# if the module is loaded again.
logger.handlers.clear()

# I keep application logs visible in the Docker container output.
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)

console_formatter = logging.Formatter(
    "%(asctime)s %(levelname)s %(name)s %(message)s"
)

console_handler.setFormatter(console_formatter)
logger.addHandler(console_handler)

# I prevent the same log record from being handled again by the root logger.
logger.propagate = False

# I create an OpenTelemetry logger provider using the same service resource.
logger_provider = LoggerProvider(
    resource=resource
)

# Application logs are exported to the Collector using OTLP over HTTP.
log_exporter = OTLPLogExporter(
    endpoint=os.getenv(
        "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",
        "http://otel-collector:4318/v1/logs"
    )
)

# I export log records in batches instead of sending them one by one.
logger_provider.add_log_record_processor(
    BatchLogRecordProcessor(log_exporter)
)

# This handler connects Python logging with the OpenTelemetry pipeline.
otel_logging_handler = LoggingHandler(
    level=logging.INFO,
    logger_provider=logger_provider
)

logger.addHandler(otel_logging_handler)


# ---------------------------------------------------------
# Database configuration
# ---------------------------------------------------------

DB_PATH = Path(os.getenv("ORDER_DB_PATH", "data/orders.db"))

STATUSES = {
    "received",
    "preparing",
    "shipped",
    "delivered"
}


def connect():
    # I make sure the database directory exists before opening SQLite.
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    db = sqlite3.connect(DB_PATH)

    # Row objects allow me to access database results using column names.
    db.row_factory = sqlite3.Row

    return db


def init_db():
    # I initialize the database when the application starts.
    with connect() as db:
        db.execute(
            """CREATE TABLE IF NOT EXISTS orders (
                id TEXT PRIMARY KEY,
                customer TEXT NOT NULL,
                item TEXT NOT NULL,
                priority TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL
            )"""
        )

        # I add sample orders only when the database is empty.
        if db.execute("SELECT COUNT(*) FROM orders").fetchone()[0] == 0:
            now = datetime.now(timezone.utc)
            previous_month_end = now.replace(day=1) - timedelta(days=1)

            for order in (
                (
                    "standard-1001",
                    "Avery",
                    "Notebook",
                    "standard",
                    "received",
                    now
                ),
                (
                    "express-1002",
                    "Sam",
                    "Headphones",
                    "express",
                    "preparing",
                    previous_month_end
                ),
                (
                    "standard-1003",
                    "Riley",
                    "Water bottle",
                    "standard",
                    "shipped",
                    now
                ),
            ):
                db.execute(
                    "INSERT INTO orders VALUES (?, ?, ?, ?, ?, ?)",
                    (*order[:5], order[5].isoformat()),
                )


def as_dict(row):
    # I convert SQLite rows into dictionaries before returning API responses.
    return dict(row) if row else None


def order_detail(row):
    order = as_dict(row)

    # Express orders include an estimated delivery date.
    if order["priority"] == "express":
        placed_at = datetime.fromisoformat(order["created_at"])
        estimated_at = placed_at + timedelta(days=2)
        order["estimated_delivery"] = estimated_at.date().isoformat()

    return order


# ---------------------------------------------------------
# API models
# ---------------------------------------------------------

class NewOrder(BaseModel):
    customer: str = Field(min_length=1, max_length=80)
    item: str = Field(min_length=1, max_length=120)
    priority: str = "standard"


class StatusUpdate(BaseModel):
    status: str


# ---------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------

@asynccontextmanager
async def lifespan(_app: FastAPI):
    # I initialize the SQLite database before serving requests.
    init_db()
    yield


app = FastAPI(
    title="Order Tracker",
    lifespan=lifespan
)

# I instrument the FastAPI application so incoming HTTP requests
# automatically create OpenTelemetry spans.
FastAPIInstrumentor.instrument_app(app)


# ---------------------------------------------------------
# API endpoints
# ---------------------------------------------------------

@app.get("/")
def index():
    # I serve the simple frontend from the static directory.
    return FileResponse(
        Path(__file__).parent.parent / "static" / "index.html"
    )


@app.get("/healthz")
def health():
    # The health endpoint also checks whether SQLite is reachable.
    with connect() as db:
        db.execute("SELECT 1")

    return {"status": "ok"}


@app.get("/api/orders")
def list_orders():
    # I return all orders with the newest orders first.
    with connect() as db:
        rows = db.execute(
            "SELECT * FROM orders ORDER BY created_at DESC"
        ).fetchall()

    return [as_dict(row) for row in rows]


@app.get("/api/orders/{order_id}")
def get_order(order_id: str):
    # I read the active span so the application log can include
    # the trace ID and span ID for correlation during an incident.
    current_span = trace.get_current_span()
    span_context = current_span.get_span_context()

    with connect() as db:
        row = db.execute(
            "SELECT * FROM orders WHERE id = ?",
            (order_id,)
        ).fetchone()

    if row is None:
        # Failed lookups are recorded as metrics with the affected
        # endpoint and HTTP status code.
        order_lookup_counter.add(
            1,
            {
                "endpoint": "/api/orders/{order_id}",
                "http.status_code": 404
            }
        )

        # I include trace information in the structured application log
        # so the failed request can be connected to its distributed trace.
        logger.warning(
            "order_lookup_failed "
            "order_id=%s status_code=%s trace_id=%s span_id=%s",
            order_id,
            404,
            format(span_context.trace_id, "032x"),
            format(span_context.span_id, "016x"),
        )

        raise HTTPException(
            status_code=404,
            detail="Order not found"
        )

    # Successful lookups are also recorded so success and failure
    # rates can be compared later in Prometheus.
    order_lookup_counter.add(
        1,
        {
            "endpoint": "/api/orders/{order_id}",
            "http.status_code": 200
        }
    )

    # I log the successful lookup with the same correlation fields.
    logger.info(
        "order_lookup_success "
        "order_id=%s status_code=%s trace_id=%s span_id=%s",
        order_id,
        200,
        format(span_context.trace_id, "032x"),
        format(span_context.span_id, "016x"),
    )

    return order_detail(row)


@app.post("/api/orders", status_code=201)
def create_order(order: NewOrder):
    # Only the two supported priority values are accepted.
    if order.priority not in {"standard", "express"}:
        raise HTTPException(
            status_code=422,
            detail="Priority must be standard or express"
        )

    order_id = str(uuid4())

    with connect() as db:
        db.execute(
            "INSERT INTO orders VALUES (?, ?, ?, ?, ?, ?)",
            (
                order_id,
                order.customer,
                order.item,
                order.priority,
                "received",
                datetime.now(timezone.utc).isoformat()
            ),
        )

    return get_order(order_id)


@app.patch("/api/orders/{order_id}")
def update_status(order_id: str, update: StatusUpdate):
    # I validate the new status before updating the database.
    if update.status not in STATUSES:
        raise HTTPException(
            status_code=422,
            detail="Invalid status"
        )

    with connect() as db:
        cursor = db.execute(
            "UPDATE orders SET status = ? WHERE id = ?",
            (update.status, order_id),
        )

    if cursor.rowcount == 0:
        raise HTTPException(
            status_code=404,
            detail="Order not found"
        )

    return get_order(order_id)
